### ISSUE TITLE
Antd Component ( Select.Option, Form.Item, Menu.Item ) only render first child

### ISSUE THREAD

**Issue by zhaohongyan** [timsayshey/vuera-react-test#8]
First, thanks your demo! 
I have some antd component only render first child, for example:
 <Select>
    <Select.Option>1</Select.Option>
    <Select.Option>2</Select.Option>
    <Select.Option>3</Select.Option>
  </Select>
only option1 has render, other options not render

antd url  [https://ant.design/components/select-cn/]

**Comment by timsayshey** [comment]
Hi, 

Unfortunately it's been too long since I've worked on this and can't really help.

I recommend you open an issue in the Vuera repo:
https://github.com/akxcv/vuera

Hope that helps!

-Tim
